version: "3.2"
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - "./.rabbitmq/data/:/var/lib/rabbitmq/"
        - "./.rabbitmq/log/:/var/log/rabbitmq"
    networks:
        - micro-unacademy
  mysql:
    container_name: 'mysql'
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - "./.mysql/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unacademy
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    networks:
      - micro-unacademy

networks:
  micro-unacademy:
    driver: bridge
